### ISSUE TITLE
Set the default platform in the dioxus.toml

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/dioxus-template#19]
The template should generate a dioxus.toml file with a default platform that is set to the platform the user choose when creating the template

**Comment by Andrew15-5** [comment]
Can I make a PR that fixes this and #26?

**Comment by ealmloff** [comment]
> Can I make a PR that fixes this and #26?

That would be great!

**Comment by Andrew15-5** [comment]
Cool. I probably make it today, because I think I'm almost done, at least with the .toml and .md files. But I gotta check other files as well.
