### ISSUE TITLE
How do I handle the `if platform` stuff in Cargo.toml?

### ISSUE THREAD

**Issue by JohnAllen** [DioxusLabs/dioxus-template#21]
- `git clone this_repo.git`
- `cd this_repo`
- `dx serve --hot-reload`

Error: Failed to load Dioxus config because: Dioxus.toml expected a table key, found a left brace at line 8 column 1

(`{% if platform == "desktop" %`}

How do I handle this {% if platform == "desktop" %} stuff?

**Comment by mrxiaozhuox** [comment]
I think you already understand this part? #22
