### ISSUE TITLE
Maybe switch back to template without subtemplates?

### ISSUE THREAD

**Issue by Andrew15-5** [DioxusLabs/dioxus-template#42]
@ealmloff once [said](https://discord.com/channels/899851952891002890/1239299296461983836/1239950180103618590):

> I don't think we should be using sub templates in the dioxus-template repo because we want to support multiple platforms at once in the future
> But it is fine for now

When I opened #26 and created #27 there were no subtemplates and `dx` didn't support it until recently (https://github.com/DioxusLabs/dioxus/pull/1872). But the default subtemplate (with `--yes`) can't be selected yet (https://github.com/cargo-generate/cargo-generate/issues/1181). I don't know about #26, but #27 is now useless, and it looks like I can remove it. Another (small) problem is that LiveView's template name [should be changed](https://discord.com/channels/899851952891002890/1204572039269326900/1204575650791428106) (small breaking change for those that already use `dx new --subtemplate` or `cargo-generate`).

One (and only?) noticeable disadvantage of not having subtemlates is that this significantly increases the number of conditions in files (and to fix #26 the way conditions are inserted in #27 isn't very nice, but manageable).

Related: #9.

**Comment by ealmloff** [comment]
The new templates support multiple platforms at once. There are still sub-templates, but each one is a different way to organize the workspace with features for all platforms
