### ISSUE TITLE
Log package conflicts

### ISSUE THREAD

**Issue by alearcy** [DioxusLabs/dioxus-template#5]
@Demonthos  @jkelleyrtp  Just installed the latest dioxus-cli after the merge, but I get a conflict error because in the cargo.toml file I got two log packages. 

`Caused by:
  TOML parse error at line 29, column 1
     |
  29 | log = "0.4.19"
     | ^
  duplicate key 'log' in table 'dependencies'`

![image](https://github.com/DioxusLabs/dioxus-template/assets/5402295/bc865d7b-4986-4595-8014-7627a54cb554)

_Originally posted by @alearcy in https://github.com/DioxusLabs/dioxus-template/issues/3#issuecomment-1664600350_

**Comment by g2p** [comment]
The automatic merge of #3 after #4 put things in the wrong order inside Cargo.toml
