### ISSUE TITLE
Support mulitple targets

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/dioxus-template#9]
Dioxus create should support setting up feature flags for each target you choose. For example, you should be able to set up a desktop and web template.

**Comment by dan-da** [comment]
Yes, as a newcomer to dioxus, having read the "one codebase, every platform" slogan I was expecting that `dioxus new` would allow me to choose multiple render targets.

**Comment by ealmloff** [comment]
The new templates support multiple platforms at once
